---

keys:
  - &admin_ewan >-
      8bdb36aa99cc27fe449b6c7ec3d536936a43caa6
  - &server_patchouli >-
      age12tyg7tv4nfq3ay0xaen5thnpgt4zesckqw3g82a7zsg66unwn3esdmgdln
  - &server_satsuki >-
      age1v97eer9wgcmrqvf449pgk73f2j55leq5ydma2w9kfqk7dmpwe5fqmy9lq8
  - &server_shinobu >-
      age13wk7pjxgem2q4twvstmr3dwju7crjhqq5l7gz6g54vav69qjf98qan7s9z

creation_rules:
  - path_regex: secrets/ewan.yaml$
    key_groups:
      - pgp:
          - *admin_ewan

  - path_regex: secrets/patchouli.yaml$
    key_groups:
      - pgp:
          - *admin_ewan
        age:
          - *server_patchouli

  - path_regex: secrets/satsuki.yaml$
    key_groups:
      - pgp:
          - *admin_ewan
        age:
          - *server_satsuki

  - path_regex: secrets/shinobu.yaml$
    key_groups:
      - pgp:
          - *admin_ewan
        age:
          - *server_shinobu
